name: Sync to GitLab
on:
  push:
    branches: [main, develop]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Push to GitLab
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/pmsplus/iqplus-devops/cicdplus-mobile.git
        git push gitlab --all
        git push gitlab --tags
